name: PortalsPE
main: Hoangg\PortalsPE\Main
api: 4.8.0
version: 3.3.3
author: Hoangg
description: 1 Plugin Cổng
permissions:
  portalspe:
    default: false
    children:
      portalspe.portal:
        default: false
      portalspe.command:
        default: false
        children:
          portalspe.command.portal:
            default: op
